"""update agents table

Revision ID: 76b6f9f1ec6b
Revises: 3b7a070f8c45
Create Date: 2026-08-06 08:36:26.412115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b6f9f1ec6b'
down_revision: Union[str, Sequence[str], None] = '3b7a070f8c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=False))
    op.add_column('agents', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('agents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    op.drop_column('agents', 'llm')
    op.drop_column('agents', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('goal', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('llm', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.alter_column('agents', 'temperature',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('agents', 'user_id')
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'system_prompt')
    op.drop_column('agents', 'description')
    # ### end Alembic commands ###
